apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-nodejs-app-summon-sidecar
  name: demo-nodejs-app-summon-sidecar
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: demo-nodejs-app-summon-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-nodejs-app-summon-sidecar
    spec:
      serviceAccountName: demo-app-summon-sidecar-sa
      containers:
        - name: demo-nodejs-app-summon-sidecar
          imagePullPolicy: IfNotPresent
          image: kanth22/summon-nodejs-app:1.6
          env:
            - name: CONJUR_AUTHN_TOKEN_FILE
              value: /run/conjur/access-token
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: conjur-connect-summon
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
              readOnly: true
            # - mountPath: /etc/summon
            #   name: summon-config
            #   readOnly: true
        - image: cyberark/conjur-kubernetes-authenticator
          name: configurator
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
          envFrom:
            - configMapRef:
                name: conjur-connect
      volumes:
        # - name: summon-config
        #   configMap:
        #     name: summon-config-sidecar
        #     defaultMode: 420
        - name: conjur-access-token
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nodejs-app-summon-sidecar
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32086
  selector:
    app: demo-nodejs-app-summon-sidecar
---